from physexp import *

a = [30]*6
print(" 平均值$ =\\frac 16 \\times (", end="")
for i in a:
    print(i, end="+")
print("\b", end="")
print(')=', end="")
print(round(Avg(a), 3), end="$")
print()
print()
print('''标准差 $\sigma=\\sqrt{\\frac{\\sum_{i=1} ^ {n}\\left(2 T_{i}-2 \\bar{T}\\right) ^ {2}}{n(n-1)}}=\\sqrt{\\frac{''')

for i in a:
    print("(", i, "-", round(Avg(a), 3), ")^2", end="+")
print("\b", end='')
print("}{n(n-1)}}=", end="")
print(round(standardDeviationOfTheMean(a), 3), end="$")
print()
print()
print(''' 平均值标准差 $\sigma_{\\bar{m}}=\sqrt{\\frac{\sum_{1}^{n}\left(m_{i}-\\bar{m}\\right)}{n(n-1)}}=0$''')
print()
print('由于六次数据相同，所以无需剔粗差')
print()
print('求出A类不确定度的值，经过查表，在 n=6，置信概率为95% 时，应该有t = 2.57')
print()
print("$U_{A}=t_{P} \\cdot \\sigma_{2 \\bar{T}}=2.57 \\times ", end="")
print(standardDeviationOfTheMean(a), end="=")
tmp = standardDeviationOfTheMean(a) * 2.57
print(round(tmp, 3), end="$")
print()
print()
print('求B类不确定度，由于测量仪器为【游标卡尺】，分度值为0.5 $10^{-3} m$')
print()
print('$U_{B}=0.05 \\times 10^{-3}$')
print()
print("$U = \\sqrt{U_A^2 + U_B^2} = \\sqrt{", end="")
print(round(tmp, 3), end="")
print("^2 + 0.0001^2} =", end="")
print(round((round(tmp, 4)**2 + 0.0005**2)**0.5, 4), end="$")
print()
print()
print("故测得的值$ = (", end="")
print(round(Avg(a), 4), end="\\pm")
print(round((round(tmp, 3)**2 + 0.05**2)**0.5, 4), end=")$")
print()